- Import the numpy package as np, so that you can refer to numpy with np.
- Use np.array() to create a numpy array from baseball. Name this array np_baseball.
- Print out the type of np_baseball to check that you got it right.

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


- Import dataset

In [2]:
import pandas as pd
data= pd.read_csv("baseball.csv")
print(type(data))
print(data.head(5))

<class 'pandas.core.frame.DataFrame'>
              Name Team       Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL        Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL        Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL        Catcher      72     210  30.78     Catcher
3     Kevin_Millar  BAL  First_Baseman      72     210  35.43   Infielder
4      Chris_Gomez  BAL  First_Baseman      73     188  35.71   Infielder


- Create a numpy array from height_in. Name this new array np_height_in.
- Print np_height_in.
- Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
- Print out np_height_m and check if the output makes sense.

In [3]:
height_in = list(data['Height'])
print(len(height_in))
print(type(height_in))

1015
<class 'list'>


In [4]:
# height_in is available as a regular list

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)


# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)


[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


- Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.
- Use np_height_m and np_weight_kg to calculate the BMI of each player. Use the following equation: bmi = weight_in_kg / height_in_m_squared
- Save the resulting numpy array as bmi.
- Print out bmi.

In [5]:
# height_in and weight_lb are available as regular lists
weight_lb = list(data['Weight'])

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)

# Print out bmi
print(bmi)



[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


- Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.
- Print the array light.
- Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array.

In [6]:
# height_in and weight_lb are available as a regular lists

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


- First of all, numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

- Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

- True is converted to 1, False is converted to 0.

In [7]:
temp = np.array([True, 1, 2]) + np.array([3, 4, False])
print(temp)

[4 5 2]


- Subset np_weight_lb by printing out the element at index 50.
- Print out a sub-array of np_height_in that contains the elements at index 100 up to and including index 110.

In [8]:
# height_in and weight_lb are available as a regular lists

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

200
[73 74 72 73 69 72 73 75 75 73 72]


- Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
- Print out the type of np_baseball.
- Print out the shape attribute of np_baseball. Use np_baseball.shape.

In [9]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


- Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
- Print out the shape attribute of np_baseball.

In [10]:
# baseball is available as a regular list of lists
baseball= [height_in, weight_lb]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)
np_baseball = np_baseball.T
print(np_baseball.shape)

(2, 1015)
(1015, 2)


- Print out the 50th row of np_baseball.
- Make a new variable, np_weight_lb, containing the entire second column of np_baseball.
- Select the height (first column) of the 124th baseball player in np_baseball and print it out.

In [11]:

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123,0])

[ 70 195]
75


- You can combine matrices with single numbers, with vectors, and with other matrices.

In [12]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

- You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254 and 0.453592. Name this array conversion.
- Multiply np_baseball with conversion and print out the result.

In [13]:
# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 1.8796  81.64656]
 [ 1.8796  97.52228]
 [ 1.8288  95.25432]
 ...
 [ 1.905   92.98636]
 [ 1.905   86.18248]
 [ 1.8542  88.45044]]


- Create numpy array np_height_in that is equal to first column of np_baseball.
- Print out the mean of np_height_in.
- Print out the median of np_height_in.

In [14]:
# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6896551724138
74.0


- The code to print out the mean height is already included. Complete the code for the median height. Replace None with the correct code.
- Use np.std() on the first column of np_baseball to calculate stddev. Replace None with the correct code.
- Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.

In [15]:

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


- A New Dataset

In [16]:
dataset = pd.read_csv("fifa.csv")
#dataset = dataset.fillna(0)
#dataset = pd.read_csv("fifa.csv", header=0)
#dataset.set_index(0, inplace=True)
print(type(dataset))
print(dataset.head(5))

<class 'pandas.core.frame.DataFrame'>
       id                     name   rating  position   height    foot   rare  \
0    1001             Gábor Király       69        GK      191   Right      0   
1  100143             Frederik Boi       65         M      184   Right      0   
2  100264          Tomasz Szewczuk       57         A      185   Right      0   
3  100325   Steeve Joseph-Reinette       63         D      180    Left      0   
4  100326             Kamel Chafni       72         M      181   Right      0   

   pace  shooting  passing  dribbling  defending  heading  diving  handling  \
0                                                              70        66   
1    61        65       63         59         62       62                     
2    65        54       43         53         55       74                     
3    68        38       51         46         64       71                     
4    75        64       67         72         57       66                     



In [19]:
heights = list(dataset[' height'])
positions = list(dataset[' position'])  
print(dataset.columns)
print(type(heights))
print(len(heights))
print(len(positions))

Index(['id', ' name', ' rating', ' position', ' height', ' foot', ' rare',
       ' pace', ' shooting', ' passing', ' dribbling', ' defending',
       ' heading', ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')
<class 'list'>
8847
8847


- Convert heights and positions, which are regular lists, to numpy arrays. Call them np_heights and np_positions.
- Extract all the heights of the goalkeepers. You can use a little trick here: use np_positions == 'GK' as an index for np_heights. Assign the result to gk_heights.
- Extract all the heights of all the other players. This time use np_positions != 'GK' as an index for np_heights. Assign the result to other_heights.
- Print out the median height of the goalkeepers using np.median(). Replace None with the correct code.
- Do the same for the other players. Print out their median height. Replace None with the correct code.

In [20]:
# heights and positions are available as lists

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
# gk_indexes = np_positions == 'GK'
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: nan
Median height of other players: 182.0


C:\Users\88016\anaconda3\envs\env_py\lib\site-packages\numpy\core\fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\88016\anaconda3\envs\env_py\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
